//client
export const GET_LIST_ADMIN = 'GET_LIST_ADMIN';
export const GET_LIST_ADMIN_SUCESS = 'GET_LIST_ADMIN_SUCESS';
export const GET_LIST_ADMIN_FAIL = 'GET_LIST_ADMIN_FAIL';

export const CREATE_ADMIN = 'CREATE_ADMIN';
export const CREATE_ADMIN_SUCESS = 'CREATE_ADMIN_SUCESS';
export const CREATE_ADMIN_FAIL = 'CREATE_ADMIN_FAIL';

export const EDIT_ADMIN = 'EDIT_ADMIN';
export const EDIT_ADMIN_SUCCESS = 'EDIT_ADMIN_SUCCESS';
export const EDIT_ADMIN_FAIL = 'EDIT_ADMIN_FAIL';

export const DELETE_ADMIN = 'DELETE_ADMIN';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';

export const GET_CHALLENGES_REPORT = 'GET_CHALLENGES_REPORT';
export const GET_CHALLENGES_REPORT_SUCCESS = 'GET_CHALLENGES_REPORT_SUCCESS';
export const GET_CHALLENGES_REPORT_FAIL = 'GET_CHALLENGES_REPORT_FAIL';

export const GET_LIST_CLIENT = 'GET_LIST_CLIENT';
export const GET_LIST_CLIENT_SUCCESS = 'GET_LIST_CLIENT_SUCCESS';
export const GET_LIST_CLIENT_FAIL = 'GET_LIST_CLIENT_FAIL';

export const GET_LIST_TRANSACTION = 'GET_LIST_TRANSACTION';
export const GET_LIST_TRANSACTION_SUCCESS = 'GET_LIST_TRANSACTION_SUCCESS';
export const GET_LIST_TRANSACTION_FAIL = 'GET_LIST_TRANSACTION_FAIL';

export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';

export const EXPORT_CHALLENGE = 'EXPORT_CHALLENGE';
export const EXPORT_CHALLENGE_SUCCESS = 'EXPORT_CHALLENGE_SUCCESS';
export const EXPORT_CHALLENGE_FAIL = 'EXPORT_CHALLENGE_FAIL';

export const EXPORT_TRANSACTION = 'EXPORT_TRANSACTION';
export const EXPORT_TRANSACTION_SUCCESS = 'EXPORT_TRANSACTION_SUCCESS';
export const EXPORT_TRANSACTION_FAIL = 'EXPORT_TRANSACTION_FAIL';