//challenge

export const CREATE_CHALLENGE = 'CREATE_CHALLENGE';
export const CREATE_CHALLENGE_SUCCESS = 'CREATE_CHALLENGE_SUCCESS';
export const CREATE_CHALLENGE_FAIL = 'CREATE_CHALLENGE_FAIL';

export const GET_LIST_CHALLENGES = 'GET_LIST_CHALLENGES';
export const GET_LIST_CHALLENGES_SUCCESS = 'GET_LIST_CHALLENGES_SUCCESS';
export const GET_LIST_CHALLENGES_FAIL = 'GET_LIST_CHALLENGES_FAIL';

export const GET_LIST_CHALLENGES_FOR_UPLOAD = 'GET_LIST_CHALLENGES_FOR_UPLOAD';
export const GET_LIST_CHALLENGES_FOR_UPLOAD_SUCCESS = 'GET_LIST_CHALLENGES_FOR_UPLOAD_SUCCESS';
export const GET_LIST_CHALLENGES_FOR_UPLOAD_FAIL = 'GET_LIST_CHALLENGES_FOR_UPLOAD_FAIL';

export const GET_CHALLENGE_BY_ID = 'GET_CHALLENGE_BY_ID';
export const GET_CHALLENGE_BY_ID_SUCCESS = 'GET_CHALLENGE_BY_ID_SUCCESS';
export const GET_CHALLENGE_BY_ID_FAIL = 'GET_CHALLENGE_BY_ID_FAIL';

export const EDIT_CHALLENGE = 'EDIT_CHALLENGE';
export const EDIT_CHALLENGE_SUCCESS = 'EDIT_CHALLENGE_SUCCESS';
export const EDIT_CHALLENGE_FAIL = 'EDIT_CHALLENGE_FAIL';

export const CHANGE_STATUS_CHALLENGE = 'CHANGE_STATUS_CHALLENGE';
export const CHANGE_STATUS_CHALLENGE_SUCCESS = 'CHANGE_STATUS_CHALLENGE_SUCCESS';
export const CHANGE_STATUS_CHALLENGE_FAIL = 'CHANGE_STATUS_CHALLENGE_FAIL';

export const GET_LIVE_CHALLENGE = 'GET_LIVE_CHALLENGE';
export const GET_LIVE_CHALLENGE_SUCCESS = 'GET_LIVE_CHALLENGE_SUCCESS';
export const GET_LIVE_CHALLENGE_FAIL = 'GET_LIVE_CHALLENGE_FAIL';

export const SEARCH_CHALLENGE = 'SEARCH_CHALLENGE';
export const SEARCH_CHALLENGE_SUCCESS = 'SEARCH_CHALLENGE_SUCCESS';
export const SEARCH_CHALLENGE_FAIL = 'SEARCH_CHALLENGE_FAIL';

export const SEARCH_DATE_CHALLENGE = 'SEARCH_DATE_CHALLENGE';
export const SEARCH_DATE_CHALLENGE_SUCCESS = 'SEARCH_DATE_CHALLENGE_SUCCESS';
export const SEARCH_DATE_CHALLENGE_FAIL = 'SEARCH_DATE_CHALLENGE_FAIL';

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAIL = 'GET_DASHBOARD_FAIL';

export const CREATOR_GET_DASHBOARD = 'CREATOR_GET_DASHBOARD';
export const CREATOR_GET_DASHBOARD_SUCCESS = 'CREATOR_GET_DASHBOARD_SUCCESS';
export const CREATOR_GET_DASHBOARD_FAIL = 'CREATOR_GET_DASHBOARD_FAIL';