//client
export const GET_LIST = 'GET_LIST';
export const GET_LIST_SUCESS = 'GET_LIST_SUCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const CREATE_CLIENT = 'CREATE_CLIENT';
export const CREATE_CLIENT_SUCESS = 'CREATE_CLIENT_SUCESS';
export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL';

export const EDIT_CLIENT = 'EDIT_CLIENT';
export const EDIT_CLIENT_SUCESS = 'EDIT_CLIENT_SUCESS';
export const EDIT_CLIENT_FAIL = 'EDIT_CLIENT_FAIL';


export const SEARCH_CLIENT = 'SEARCH_CLIENT';
export const SEARCH_CLIENT_SUCESS = 'SEARCH_CLIENT_SUCESS';
export const SEARCH_CLIENT_FAIL = 'SEARCH_CLIENT_FAIL';

export const RESET_DATA_CLIENT = 'RESET_DATA_CLIENT';

export const EXPORT_CLIENT = 'EXPORT_CLIENT';
export const EXPORT_CLIENT_SUCESS = 'EXPORT_CLIENT_SUCESS';
export const EXPORT_CLIENT_FAIL = 'EXPORT_CLIENT_FAIL';

export const EXPORT_EXCEL_CLIENT = 'EXPORT_EXCEL_CLIENT';
export const EXPORT_EXCEL_CLIENT_SUCESS = 'EXPORT_EXCEL_CLIENT_SUCESS';
export const EXPORT_EXCEL_CLIENT_FAIL = 'EXPORT_EXCEL_CLIENT_FAIL';

export const EXPORT_CSV_CLIENT = 'EXPORT_CSV_CLIENT';
export const EXPORT_CSV_CLIENT_SUCESS = 'EXPORT_CSV_CLIENT_SUCESS';
export const EXPORT_CSV_CLIENT_FAIL = 'EXPORT_CSV_CLIENT_FAIL';

export const GET_SOCIAL_MEDIA = 'GET_SOCIAL_MEDIA';
export const GET_SOCIAL_MEDIA_SUCCESS = 'GET_SOCIAL_MEDIA_SUCCESS';
export const GET_SOCIAL_MEDIA_FAIL = 'GET_SOCIAL_MEDIA_FAIL';

export const GET_LIST_CREATORS = 'GET_LIST_CREATORS';
export const GET_LIST_CREATORS_SUCCESS = 'GET_LIST_CREATORS_SUCCESS';
export const GET_LIST_CREATORS_FAIL = 'GET_LIST_CREATORS_FAIL';

export const SEND_MAILTO_CREATOR = 'SEND_MAILTO_CREATOR';
export const SEND_MAILTO_CREATOR_SUCCESS = 'SEND_MAILTO_CREATOR_SUCCESS';
export const SEND_MAILTO_CREATOR_FAIL = 'SEND_MAILTO_CREATOR_FAIL';
export const SET_FACEBOOK_PAGES = 'SET_FACEBOOK_PAGES';
export const SET_FACEBOOK_PAGES_SUCCESS = 'SET_FACEBOOK_PAGES_SUCCESS';
export const SET_FACEBOOK_PAGES_FAIL = 'SET_FACEBOOK_PAGES_FAIL';

export const POST_FACEBOOK = 'POST_FACEBOOK';
export const POST_FACEBOOK_SUCCESS = 'POST_FACEBOOK_SUCCESS';
export const POST_FACEBOOK_FAIL = 'POST_FACEBOOK_FAIL';

export const POST_TWITTER = 'POST_TWITTER';
export const POST_TWITTER_SUCCESS = 'POST_TWITTER_SUCCESS';
export const POST_TWITTER_FAIL = 'POST_TWITTER_FAIL';

export const LOGOUT_TWITTER = 'LOGOUT_TWITTER';
export const LOGOUT_TWITTER_SUCCESS = 'LOGOUT_TWITTER_SUCCESS';
export const LOGOUT_TWITTER_FAIL = 'LOGOUT_TWITTER_FAIL';

export const REWARD_LIST = 'REWARD_LIST';
export const REWARD_LIST_SUCCESS = 'REWARD_LIST_SUCCESS';
export const REWARD_LIST_FAIL = 'REWARD_LIST_FAIL';

export const GET_LIST_CREATORS_REWARDEES = 'GET_LIST_CREATORS_REWARDEES';
export const GET_LIST_CREATORS_REWARDEES_SUCCESS = 'GET_LIST_CREATORS_REWARDEES_SUCCESS';
export const GET_LIST_CREATORS_REWARDEES_FAIL = 'GET_LIST_CREATORS_REWARDEES_FAIL';

export const GET_CONFIGURE_MAIL = 'GET_CONFIGURE_MAIL';
export const GET_CONFIGURE_MAIL_SUCCESS = 'GET_CONFIGURE_MAIL_SUCCESS';
export const GET_CONFIGURE_MAIL_FAIL = 'GET_CONFIGURE_MAIL_FAIL';

export const UPDATE_CONFIGURE_MAIL = 'UPDATE_CONFIGURE_MAIL';
export const UPDATE_CONFIGURE_MAIL_SUCCESS = 'UPDATE_CONFIGURE_MAIL_SUCCESS';
export const UPDATE_CONFIGURE_MAIL_FAIL = 'UPDATE_CONFIGURE_MAIL_FAIL';

export const CHANGE_TEMPLATE_STATUS = 'CHANGE_TEMPLATE_STATUS';
export const CHANGE_TEMPLATE_STATUS_SUCCESS = 'CHANGE_TEMPLATE_STATUS_SUCCESS';
export const CHANGE_TEMPLATE_STATUS_FAIL = 'CHANGE_TEMPLATE_STATUS_FAIL';

export const EXPORT_CREATOR = 'EXPORT_CREATOR'
export const EXPORT_CREATOR_SUCCESS = 'EXPORT_CREATOR_SUCCESS'
export const EXPORT_CREATOR_FAIL = 'EXPORT_CREATOR_FAIL'

export const IMPORT_CREATOR = 'IMPORT_CREATOR'
export const IMPORT_CREATOR_SUCCESS = 'IMPORT_CREATOR_SUCCESS'
export const IMPORT_CREATOR_FAIL = 'IMPORT_CREATOR_FAIL'

export const EXPORT_REWARDEE = 'EXPORT_REWARDEE'
export const EXPORT_REWARDEE_SUCCESS = 'EXPORT_REWARDEE_SUCCESS'
export const EXPORT_REWARDEE_FAIL = 'EXPORT_REWARDEE_FAIL'

export const CREATE_TEMPLATE = 'CREATE_TEMPLATE'
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS'
export const CREATE_TEMPLATE_FAIL = 'CREATE_TEMPLATE_FAIL'

export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS'
export const DELETE_TEMPLATE_FAIL = 'DELETE_TEMPLATE_FAIL'