//content
export const CREATOR_UPLOAD = 'CREATOR_UPLOAD';
export const CREATOR_UPLOAD_SUCCESS = 'CREATOR_UPLOAD_SUCCESS';
export const CREATOR_UPLOAD_FAIL = 'CREATOR_UPLOAD_FAIL';

export const CREATOR_GET_LIST_UPLOAD = 'CREATOR_GET_LIST_UPLOAD';
export const CREATOR_GET_LIST_UPLOAD_SUCCESS = 'CREATOR_GET_LIST_UPLOAD_SUCCESS';
export const CREATOR_GET_LIST_UPLOAD_FAIL = 'CREATOR_GET_LIST_UPLOAD_FAIL';

export const CREATOR_GET_UPLOAD = 'CREATOR_GET_UPLOAD';
export const CREATOR_GET_UPLOAD_SUCCESS = 'CREATOR_GET_UPLOAD_SUCCESS';
export const CREATOR_GET_UPLOAD_FAIL = 'CREATOR_GET_UPLOAD_FAIL';

export const CONTENT_REVIEW_UPDATE = 'CONTENT_REVIEW_UPDATE';
export const CONTENT_REVIEW_UPDATE_SUCCESS = 'CONTENT_REVIEW_UPDATE_SUCCESS';
export const CONTENT_REVIEW_UPDATE_FAIL = 'CONTENT_REVIEW_UPDATE_FAIL';

export const CONTENT_REWARD_LIST = 'CONTENT_REWARD_LIST';
export const CONTENT_REWARD_LIST_SUCCESS = 'CONTENT_REWARD_LIST_FAIL';
export const CONTENT_REWARD_LIST_FAIL = 'CONTENT_REWARD_LIST_FAIL';

export const CONTENT_REWARD_UPDATE = 'CONTENT_REWARD_UPDATE';
export const CONTENT_REWARD_UPDATE_SUCCESS = 'CONTENT_REWARD_UPDATE_SUCCESS';
export const CONTENT_REWARD_UPDATE_FAIL = 'CONTENT_REWARD_UPDATE_FAIL';

export const CONTENT_SEARCH = 'CONTENT_SEARCH';
export const CONTENT_SEARCH_SUCCESS = 'CONTENT_SEARCH_SUCCESS';
export const CONTENT_SEARCH_FAIL = 'CONTENT_SEARCH_FAIL';

export const RATING_MULTIPLE_CONTENT = 'RATING_MULTIPLE_CONTENT';
export const RATING_MULTIPLE_CONTENT_SUCCESS = 'RATING_MULTIPLE_CONTENT_SUCCESS';
export const RATING_MULTIPLE_CONTENT_FAIL = 'RATING_MULTIPLE_CONTENT_FAIL';