export const EXPORT_REWARD_CLIENT = 'EXPORT_REWARD_CLIENT';
export const EXPORT_REWARD_CLIENT_SUCCESS = 'EXPORT_REWARD_CLIENT_SUCCESS';
export const EXPORT_REWARD_CLIENT_FAIL = 'EXPORT_REWARD_CLIENT_FAIL';

export const IMPORT_REWARD_CLIENT = 'IMPORT_REWARD_CLIENT';
export const IMPORT_REWARD_CLIENT_SUCCESS = 'IMPORT_REWARD_CLIENT_SUCCESS';
export const IMPORT_REWARD_CLIENT_FAIL = 'IMPORT_REWARD_CLIENT_FAIL';