//reviewers
const GET_LIST_REVIEWERS = 'GET_LIST_REVIEWERS';
const GET_LIST_REVIEWERS_SUCESS = 'GET_LIST_REVIEWERS_SUCESS';
const GET_LIST_REVIEWERS_FAIL = 'GET_LIST_REVIEWERS_FAIL';

const CREATE_REVIEWERS = 'CREATE_REVIEWERS';
const CREATE_REVIEWERS_SUCESS = 'CREATE_REVIEWERS_SUCESS';
const CREATE_REVIEWERS_FAIL = 'CREATE_REVIEWERS_FAIL';

const EDIT_REVIEWERS = 'EDIT_REVIEWERS';
const EDIT_REVIEWERS_SUCCESS = 'EDIT_REVIEWERS_SUCCESS';
const EDIT_REVIEWERS_FAIL = 'EDIT_REVIEWERS_FAIL';

const DELETE_REVIEWERS = 'DELETE_REVIEWERS';
const DELETE_REVIEWERS_SUCCESS = 'DELETE_REVIEWERS_SUCCESS';
const DELETE_REVIEWERS_FAIL = 'DELETE_REVIEWERS_FAIL';

export {
  GET_LIST_REVIEWERS,
  GET_LIST_REVIEWERS_SUCESS,
  GET_LIST_REVIEWERS_FAIL,
  CREATE_REVIEWERS,
  CREATE_REVIEWERS_SUCESS,
  CREATE_REVIEWERS_FAIL,
  EDIT_REVIEWERS,
  EDIT_REVIEWERS_SUCCESS,
  EDIT_REVIEWERS_FAIL,
  DELETE_REVIEWERS,
  DELETE_REVIEWERS_SUCCESS,
  DELETE_REVIEWERS_FAIL
}