export const UPLOAD_WIDGET = 'UPLOAD_WIDGET';
export const UPLOAD_WIDGET_SUCCESS = 'UPLOAD_WIDGET_SUCCESS';
export const UPLOAD_WIDGET_FAIL = 'UPLOAD_WIDGET_FAIL';

export const CHECK_EMAIL = 'CHECK_EMAIL';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAIL = 'CHECK_EMAIL_FAIL';
